package xendroid.compose.settings

/**
 * One-line, user-facing descriptions per setting name, shown as a long-press
 * tooltip. Sourced from the native cvar help strings (condensed); a few
 * app-only entries are written from usage. Injected into [Setting.desc] by the
 * schema helpers.
 */
object SettingDescriptions {
    val byName: Map<String, String> = mapOf(
        "accurate_resolve_number_formats" to "Handle signed/integer resolve destinations and gamma-decode 8_8_8_8_GAMMA sources; a few titles need it, but it enlarges every full resolve shader and costs significant frame rate on mobile GPUs",
        "adrenotools_force_max_clocks" to "Force the GPU to its maximum clocks via the custom driver; more speed, more heat and battery drain",
        "allow_incompatible_title_update" to "Applies title updates even when their signature doesn't match the game",
        "allow_plugins" to "Allows loading homebrew plugin/trainer XEX modules per title; experimental",
        "android_soft_keyboard" to "Pops up the Android keyboard when a game asks you to type (gamertags, save names). With this off the game is answered with its own default text",
        "apply_patches" to "Applies user patch files to games when they load",
        "apply_title_update" to "Applies installed title updates when launching a game",
        "apu" to "Audio output backend to use (AAudio, OpenSL ES, or no audio)",
        "apu_aaudio_buffer_bursts" to "How much audio the device buffers ahead. Lower means less audio delay; too low and audio breaks up on slower devices",
        "apu_max_queued_frames" to "Max buffered audio frames (4-64); lower cuts audio delay but may cause stutter",
        "avpack" to "Emulated AV cable/connection type reported to games (component, SCART, HDMI, VGA, etc.)",
        "break_condition_truncate" to "Truncates the conditional-breakpoint register value to 32 bits before comparing",
        "break_on_start" to "Breaks into the debugger as soon as the emulator starts",
        "break_on_unimplemented_instructions" to "Breaks into the debugger (or crashes) when an unimplemented PowerPC instruction is hit",
        "clear_memory_page_state" to "Refresh memory page state so GPU-written data is visible; off is slightly faster but may break rendering",
        "clock_no_scaling" to "Bypasses guest clock scaling and pulls time straight from the host; ignores time scalar",
        "clock_source_raw" to "Uses the raw CPU counter (CNTVCT) as the time source instead of OS clock calls",
        "collapse_memory_delay_spins" to "Skips guest busy-wait delay loops that count a stack counter down to zero, jumping straight to the end state. Big CPU saving in games that use long delays. It does shorten a real wait, so turn it off for a game that misbehaves with it on. Takes effect next time a game starts",
        "depth_float24_convert_in_pixel_shader" to "Convert depth to 24-bit float in pixel shaders; fixes striped depth artifacts at some speed cost",
        "depth_float24_round" to "Round to nearest instead of truncating when converting depth to 24-bit float; off is recommended",
        "depth_transfer_not_equal_test" to "Skip rewriting unchanged depth during depth transfers to keep depth compression effective",
        "disable_context_promotion" to "Turns off a CPU optimization that some sports games depend on being absent; fixes them at a cost to performance. Takes effect next time a game starts",
        "draw_resolution_scale_x" to "The real resolution scale: renders the game at this multiple of its native width. Whole steps only, and it cannot go below 1x. Costs GPU time and memory",
        "draw_resolution_scale_y" to "The real resolution scale: renders the game at this multiple of its native height. Whole steps only, and it cannot go below 1x. Costs GPU time and memory",
        "draw_resolution_scale_factor" to "A secondary multiplier for the internal rendering resolution (0.25x to 1.0x). Use this to downscale the resolution below native to boost performance on low-end devices",
        "draw_resolution_scaled_texture_offsets" to "Scale texture fetch offsets with the resolution scale for more correct shadows and bloom",
        "dump_session_logs" to "Exports this session's emulator log and logcat as a zip to Downloads",
        "enable_3d_mode" to "Lets titles enable stereoscopic 3D output if they support it",
        "enable_xmp" to "Enables Xbox 360 Music Player playback",
        "execute_unclipped_draw_vs_on_cpu" to "Run unclipped draws' vertex shaders on the CPU to estimate EDRAM use; faster and avoids corruption",
        "execute_unclipped_draw_vs_on_cpu_for_psi_render_backend" to "Also apply CPU vertex-shader extent estimation with the pixel shader interlock backend; fewer barriers",
        "execute_unclipped_draw_vs_on_cpu_with_scissor" to "Run CPU vertex-shader extent estimation even on scissored unclipped draws; may add CPU cost",
        "ffmpeg_verbose" to "Enables verbose FFmpeg output in the log for audio decoding",
        "flush_log" to "Flushes the log file after each batch of lines; keeps crash logs intact but slightly slower",
        "force_convert_quad_lists_to_triangle_lists" to "Always convert quad lists to triangles on the CPU even when the GPU can draw them natively",
        "force_convert_triangle_fans_to_lists" to "Always convert triangle fans to triangle lists on the CPU even when the GPU supports fans",
        "gpu" to "Graphics backend to use for rendering (Vulkan or null)",
        "gpu_stall_spin_iterations" to "How long the graphics thread busy-waits for the game to send more work before going to sleep. Lower frees up a CPU core and cuts heat; too low can add a little latency to each batch of drawing. 0 sleeps immediately",
        "framerate_limit" to "Caps how many frames the emulator presents per second. The console never went above 60, so frames beyond your screen's refresh are just heat and battery. Unlimited lets it run as fast as it can",
        "gpu_allow_invalid_fetch_constants" to "Tolerate invalid texture/vertex fetch constants instead of failing; works around errors in some games",
        "guest_display_refresh_cap" to "Cap vblanks at the console's 50/60Hz rate; off lets the game run as fast as possible",
        "guest_scheduler" to "Run guest threads as cooperative fibers on a few host threads instead of one thread each; takes effect next launch",
        "guest_scheduler_stats" to "Log scheduler counters once a second; use to check re-poll rate and I/O queueing when diagnosing stalls",
        "guest_scheduler_quantum_us" to "How long a guest thread runs before yielding to another; lower is fairer but switches more often",
        "half_pixel_offset" to "Emulate the console's half-pixel offset; correct for most games, off may fix slight UI blur in a few",
        "headless" to "Suppresses in-game system dialogs, answering prompts automatically with defaults. Text-entry prompts are exempt while the Android keyboard setting is on",
        "hid" to "Input backend used for controllers; 'any' picks the first one available",
        "ignore_offset_for_ranged_allocations" to "Drops the 4K offset on ranged physical allocations; some games require the exact lower address",
        "ignore_thread_affinities" to "Ignores game-requested CPU core pinning and lets the host schedule threads freely",
        "ignore_thread_priorities" to "Ignores game-requested thread priorities and lets the host schedule threads normally",
        "inline_mmio_access" to "Inlines constant-address hardware (MMIO) loads and stores into compiled code for speed",
        "interlaced" to "Reports an interlaced video mode to games instead of progressive scan",
        "internal_display_resolution" to "Not a scaler: it only tells the game what the TV is. Most titles render at a fixed size and ignore it, so the picture usually will not change. For higher detail use Resolution scale under GPU",
        "kernel_cert_monitor" to "Reports the certification monitor as present to the game (debug/testing feature)",
        "kernel_debug_monitor" to "Reports a debug monitor (remote debugger) as attached to the game",
        "kernel_display_gamma_type" to "Display gamma curve reported to games; BT.709 best matches a 360 on an HDTV",
        "kernel_pix" to "Exposes the PIX GPU profiler interface to the game for debug captures",
        "license_mask" to "Content license mask: 0 = none, 1 = full-version license (unlocks XBLA trials), -1 = all",
        "log_safepoint_pc" to "Records where each guest thread last reached a yield point, so a freeze report can say where a stuck thread actually is instead of only where it last called from. Slows the emulator slightly; turn on only when chasing a freeze",
        "log_delay_collapse_rejects" to "Logs each delay loop that the collapse looked at and turned down, with the reason. Diagnostic aid for working out why a game sees no benefit; noisy while a game is loading",
        "log_guest_driven_gpu_register_written_values" to "Log every GPU register write made by the guest (debug builds only)",
        "log_high_frequency_kernel_calls" to "Logs even very frequent kernel calls; extremely verbose and slows things down",
        "log_level" to "Maximum log verbosity: 0 errors, 1 warnings, 2 info, 3 debug",
        "log_ringbuffer_kickoff_initiator_bts" to "Log a pseudo-stacktrace of the guest thread that kicked off the ringbuffer (debug builds only)",
        "log_sessions_keep" to "How many past sessions' log zips to keep in the logs folder before old ones are rotated out",
        "log_string_format_kernel_calls" to "Logs guest calls to kernel string formatters like sprintf",
        "mmap_address_high" to "High address slot (1-124, in 4GB steps) for guest memory; change if mappings collide and crash",
        "mount_cache" to "Mounts the cache: drive games use for cached data; some titles need it to run properly",
        "mount_scratch" to "Mounts the scratch: drive some games use for temporary files",
        "mrt_edram_used_range_clamp_to_min" to "With multiple render targets, estimate EDRAM writes conservatively to reduce copying between them",
        "mute" to "Silences all audio output",
        "native_2x_msaa" to "Use the GPU's real 2x MSAA when available instead of emulating it with 4x samples",
        "non_seamless_cube_map" to "Skip filtering across cube map face edges where possible to match Direct3D 9 behavior",
        "occlusion_query" to "How visibility queries (lens flares, culling, auto-exposure) are answered: faked, async, or exact",
        "postprocess_antialiasing" to "Apply FXAA post-process anti-aliasing to smooth edges; recommended when CAS or FSR is active",
        "postprocess_dither" to "Dither the final image down to 8-bit color for smoother gradients; disable on true 10-bit displays",
        "postprocess_scaling_and_sharpening" to "Upscaling filter for the final image, from plain bilinear to AMD CAS sharpening or FSR upscaling",
        "present_letterbox" to "Keep the game's aspect ratio by adding black bars instead of stretching to fill the screen",
        "present_render_pass_clear" to "Clear the whole screen via the render pass instead of separate clears of the letterbox bars",
        "protect_on_release" to "Locks freed memory so any later access faults, catching use-after-free bugs",
        "protect_zero" to "Blocks reads and writes to the zero page so null-pointer accesses fault instead of corrupting",
        "readback_memexport" to "Read shader memory-export data back to the CPU; some games need it, off is slightly faster",
        "readback_resolve" to "Which resolves are copied back to guest RAM; UMA reads mapped memory directly and is the only mode that works on Adreno",
        "render_target_path" to "Render target emulation path: fast fixed-function or slower pixel-exact software blending",
        "resolve_copy_dest_number_packing" to "Packs full-resolve destinations by copy_dest_number instead of assuming an unsigned fraction; only has an effect with accurate resolve number formats on",
        "resolve_resolution_scale_fill_half_pixel_offset" to "With resolution scaling, patch edge gaps from the half-pixel offset; some games need it to render",
        "scribble_heap" to "Fills newly allocated heap memory with a junk value to expose uninitialized-memory bugs",
        "show_achievement_notification" to "Shows a pop-up notification on screen when you unlock an achievement",
        "show_debug_overlay" to "Show an on-screen overlay with FPS, frame times, and in-flight shader compiles",
        "snorm16_render_target_full_range" to "Remap 16-bit render targets to keep their full value range at some cost to blending correctness",
        "staging_mode" to "Runs dashboards in staging/preview mode so they render extra debug information",
        "storage_selection_dialog" to "Shows a storage device picker when a game asks; off auto-selects a device",
        "store_all_context_values" to "Keeps dead register stores in JIT output to aid debugging, at a performance cost",
        "store_shaders" to "Save compiled shaders to disk so later sessions skip compile stutter and freezes",
        "texture_cache_memory_limit_hard" to "Host texture memory cap in MB; textures above it are destroyed as soon as possible",
        "texture_cache_memory_limit_soft" to "Texture cache size in MB above which old unused textures start being evicted",
        "texture_gradient_exp_bias" to "Honor per-axis mipmap bias when sampling; more accurate but adds shader cost to every gradient texture fetch",
        "texture_integer_num_format" to "Rescale integer-format textures to guest units; more accurate but adds shader cost to every affected texture fetch",
        "time_scalar" to "Speeds up or slows down guest time (1 = normal, 2 = double speed, 0.5 = half)",
        "trace_function_coverage" to "Records per-instruction coverage statistics for compiled functions; developer debugging aid",
        "trace_function_references" to "Records function address references during JIT compilation for developer analysis",
        "trace_gpu_stream" to "Trace all GPU command packets for debugging; very slow",
        "turnip_debug" to "Comma-separated TU_DEBUG flags for the Turnip driver; e.g. sysmem disables tiled rendering (Turnip only)",
        "use_50Hz_mode" to "Runs PAL games in 50Hz (PAL-50) mode instead of 60Hz",
        "use_dedicated_xma_thread" to "Decodes XMA audio on its own thread; disabling may sound better but costs performance",
        "user_country" to "Console country/region ID reported to games",
        "user_language" to "Console language ID reported to games (1=English, 2=Japanese, 3=German, ...)",
        "validate_hir" to "Runs extra validation on the JIT's intermediate code during compilation; slow, for debugging",
        "value_convert_7e3_8888_reuse" to "Decode HDR EDRAM tiles reused as 8-bit color before blending, avoiding garbage-colored backgrounds",
        "video_standard" to "Video signal standard the console reports (NTSC, NTSC-J, or PAL); can affect region behavior",
        "vulkan_allow_present_mode_fifo_relaxed" to "Allow relaxed vsync presentation, which may tear when frames miss the display refresh rate",
        "vulkan_allow_present_mode_immediate" to "Allow immediate presentation for lowest latency, at the cost of possible tearing",
        "vulkan_allow_present_mode_mailbox" to "Allow mailbox presentation, giving low latency without tearing when the driver supports it",
        "vulkan_async_skip_draws" to "Drop draws whose shaders are still compiling instead of waiting; brief pop-in instead of stutter",
        "vulkan_cache_texture_descriptors" to "Reuse texture/sampler descriptor sets across unchanged draws; disable to debug texture corruption",
        "vulkan_dynamic_pipeline_state" to "Use dynamic state for cull/depth/blend to cut pipeline permutations and shader-compile stutter",
        "vulkan_in_pass_resolve" to "Resolve EDRAM copies inside the render pass on tiled GPUs, avoiding a pass break per resolve",
        "vulkan_placeholder_pipelines" to "Render a stand-in shader while the real one compiles, instead of skipping the draw until it is ready",
        "vulkan_resolve_to_texture" to "Have in-pass resolves write the destination texture directly; needs the promote toggle, pairs with skip upload",
        "vulkan_resolve_to_texture_promote" to "Allocate resolve-target textures so a resolve can write them directly; costs framebuffer compression on those textures",
        "vulkan_resolve_to_texture_serve" to "Skip re-uploading textures an in-pass resolve already filled this frame; this is where the round-trip traffic disappears",
        "vulkan_lib_path" to "Path to a custom Vulkan driver library (e.g. Turnip) to load instead of the system driver",
        "vulkan_log_debug_messages" to "Write Vulkan debug-utils messages to the emulator log instead of the system debug output",
        "vulkan_mid_frame_submission_draws" to "Submit GPU work after this many draws instead of once per frame; 0 off, too low hurts tiled GPUs",
        "vulkan_pipeline_creation_threads" to "Threads used to build graphics pipelines: -1 auto, 0 single-threaded, or an explicit count",
        "vulkan_renderdoc_capture" to "Load the RenderDoc capture layer so frames can be captured by attaching from qrenderdoc",
        "vulkan_sparse_shared_memory" to "Use sparse binding for guest memory; disabling uses a full 512 MB buffer but helps some GPU debuggers",
        "vulkan_texture_descriptor_reuse_edge" to "Use upstream's descriptor reuse check instead of the content-hash one, for A/B comparison",
        "vulkan_validation" to "Vulkan validation level: off, standard, +synchronization, +GPU-assisted; higher catches more bugs but is much slower",
        "widescreen" to "Reports a 16:9 display to games instead of 4:3, controlling their aspect ratio",
        "writable_executable_memory" to "Allows memory that is both writable and executable, mimicking platforms that permit it",
        "xma_decoder" to "Which XMA audio decoder to use, trading stability against legacy Xenia behavior",
        "xmp_default_volume" to "Default music player volume (0-100) used when the game doesn't set one",
    )
}
